### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by HuiiBuh** [HuiiBuh/spotify-playlist-colloboration#64]
Things I have to do:
- [x] Angular API wrapper
- [x] Scroll to right position
- [x] Playback controls
- [ ] Login required
- [ ] Security
- [ ] User Error and Success Messages
- [ ] Total time calculation
- [ ] Mobile UI
- [ ] Background image
- [ ] Background colon
- [ ] Preload next image through proxy
